#%RAML 1.0 NamedExample
value:
  dealerCode: F_121020
  dealerReference: TestReference
  type: Delivery
  placed: 2018-05-15T16:14:58Z
  items:
    - 
      brandName: Bridgestone
      partNo: "000222"
      warehouseId: "100"
      qty: 3
    - 
      brandName: Goodyear
      partNo: "000333"
      warehouseId: "101"
      qty: 6


