#%RAML 1.0 NamedExample
value:
-
  id: "2"
  items: 
    -
      brandName: Bridgestone
      partNo: "0000222"
      qty: 3
  status: Processing
  estDelivery: 2018-05-15T00:00:00Z
  warehouse: 
    -
      warehouseId: "2"
      name: name
      address: address
      address2: address2
      city: city
      state: FL
      postalCode: "33169"
  pickupPhone: "123"

